apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: techdocs-test
  description: Test component for TechDocs
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/annelson-rh/techdocs-test
spec:
  type: documentation
  lifecycle: experimental
  owner: guests
